#+BRAIN_PARENTS: index

If you're being unfaithful it's evil
certainly.

But the world will try to make you feel evil
for the purpose of distracting you from what
is truly evil.

If you are being unfaithful, whether that is
to your spouse or to God, that is evil.

What goes in does not defile you - what comes
out does.

Porn is evil if you progressively increase the
strangeness of it or degenerate.

If you're saved you begin to eliminate things
which prevent you from being faithful to God
and to others.

If porn is causing you to sin then you'll
remove it.

Sin is damaging relationship with God.

Don't separate the concept of sin from the
concept of a relationship with God.

It's not strictly true that Pornography is
evil.

Nothing is unclean in itself (ROMANS 14:13-18)
The truth is that if you are doing this within
the divine precepts you are not sinning.

What is truly degenerate is being unfaithful
(adulterating with the heart).

Now if you have been faithful and are forced
into this situation, it's not your fault
you're watching porn.

Society is broken, not the person.

* intrinsically evil
  :PROPERTIES:
  :ID:       1432a256-e4c0-48b1-8476-b9d3665b3644
  :END:

Some people say it's inherently wrong.

[[https://www.youtube.com/watch?v=GQymc1uyUaE][Pope Francis's Comments on Pornography - YouTube]]

The reason is that it takes an inappropriate attitude towards the human person.

* desentitisation
  :PROPERTIES:
  :ID:       e8d52226-2429-404d-95eb-b2ee6c73fb3f
  :END:

- https://mullikine.github.io/posts/a-vision-of-sin/

- [[https://www.youtube.com/watch?v=hVxtZ4tDjOc]["Porn will DESTROY YOU!!" {How to escape a porn addiction} - Jordan Peterson Motivation - YouTube]]

Desensitisation also happens.

I think of it like the degeneration of
innocence, and the perversion of what is
'normal' at a social level.

But the human race is responding 'normally' to
overstimuli.

The story of S&G in genesis represents an
inversion of minority with majority - total
social degeneration.

I think people have to find a way through into
the future whilst being faithful and
maintaining a relationship with God, instead
of deciding the relationship with God is
impossible because we can't decide what is
sinful.

So use a reductionist and practical approach
and stay faithful, and try not to degenerate.

https://mullikine.github.io/posts/a-vision-of-sin/